server:
    port: 8080

spring:
# freemarker默认读取templates目录的模版文件,默认为ftl(jsp,html,ftl)，和static下的静态资源文件（js,css）,此处自定义为html后缀名
    freemarker:
        prefix:
        suffix: .html
    # redis配置
    redis:
        #redis数据库名称  从0到15,默认为db0
        database: 0
        # 连接redis的密码,requirpass(跟redis的master和slave同步密码masterauth两回事)
        password: ptmind
        sentinel:
          # master的名字是在哨兵进程里定义的
          master: mymaster
          nodes: 172.16.100.81:6378,172.16.100.81:6379,172.16.100.81:26379
---
spring:
    profiles: dev
datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/huan_blog?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    maximumPoolSize: 10
---
spring:
    profiles: test
    # redis配置
    redis:
        #redis数据库名称  从0到15,默认为db0
        database: 0
        # 连接redis的密码,requirpass(跟redis的master和slave同步密码masterauth两回事)
        password:
        sentinel:
          # master的名字是在哨兵进程里定义的
          master: master
          nodes: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:26379
datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/huan_blog?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    maximumPoolSize: 10
---
spring:
    profiles: prod
datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/huan_blog_prod?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    maximumPoolSize: 10